FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/node:20.11.1-slim as build

WORKDIR /zklink-nova-echosystem

RUN apt update -y

RUN apt install -y python-is-python3

ADD . /zklink-nova-echosystem

RUN npm install && npm run build

FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:alpine3.18

RUN mkdir /build

COPY --from=build /zklink-nova-echosystem/build /build

#CMD ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
